window.hjSiteSettings = window.hjSiteSettings || {"testers_widgets":[],"surveys":[],"record_targeting_rules":[{"negate":false,"pattern":"http:\/\/www.blurb.com\/getting-started","match_operation":"simple","component":"url"},{"negate":false,"pattern":"http:\/\/www.blurb.com\/mobile","match_operation":"simple","component":"url"},{"negate":false,"pattern":"http:\/\/www.blurb.com\/bookwright-install-mac-3","match_operation":"simple","component":"url"},{"negate":false,"pattern":"http:\/\/www.blurb.com\/bookwright-install-pc-3","match_operation":"simple","component":"url"}],"recording_capture_keystrokes":true,"polls":[],"site_id":7575,"forms":[],"record":true,"heatmaps":[{"created_epoch_time":1478208675,"targeting":[{"negate":false,"pattern":"http:\/\/www.blurb.com\/mobile","match_operation":"simple","component":"url"}],"id":888385},{"created_epoch_time":1475708821,"targeting":[{"negate":false,"pattern":"http:\/\/www.blurb.com\/cookbooks","match_operation":"starts_with","component":"url"}],"id":814683},{"created_epoch_time":1464130364,"targeting":[{"negate":false,"pattern":"http:\/\/www.blurb.com\/business","match_operation":"simple","component":"url"}],"id":545743},{"created_epoch_time":1460398776,"targeting":[{"negate":false,"pattern":"http:\/\/www.blurb.com\/bookstore\/ebooks\/new","match_operation":"simple","component":"url"}],"id":463910},{"created_epoch_time":1456768040,"targeting":[{"negate":false,"pattern":"http:\/\/www.blurb.com\/instruction","match_operation":"simple","component":"url"}],"id":388891},{"created_epoch_time":1446772279,"targeting":[{"negate":false,"pattern":"http:\/\/www.blurb.com\/bookswithbite25","match_operation":"simple","component":"url"}],"id":230906},{"created_epoch_time":1436816115,"targeting":[{"negate":false,"pattern":"http:\/\/www.blurb.com\/kids-photo-books","match_operation":"simple","component":"url"}],"id":115302},{"created_epoch_time":1436552687,"targeting":[{"negate":false,"pattern":"http:\/\/www.blurb.com\/gifts\/travel-journal","match_operation":"simple","component":"url"}],"id":114135},{"created_epoch_time":1436552552,"targeting":[{"negate":false,"pattern":"http:\/\/www.blurb.com\/travel-books","match_operation":"simple","component":"url"}],"id":114133},{"created_epoch_time":1433796607,"targeting":[{"negate":false,"pattern":"http:\/\/www.blurb.com\/covers-and-bindings","match_operation":"simple","component":"url"}],"id":92489},{"created_epoch_time":1433370908,"targeting":[{"negate":false,"pattern":"http:\/\/www.blurb.com\/offset-printing","match_operation":"simple","component":"url"}],"id":89781}],"deferred_page_contents":[],"feedback_widgets":[],"r":0.1933155759};

window.hjBootstrap = window.hjBootstrap || function (scriptUrl) {
    var s = document.createElement('script');
    s.src = scriptUrl;
    document.getElementsByTagName('head')[0].appendChild(s);
    window.hjBootstrap = function() {};
};

hjBootstrap('https://script.hotjar.com/modules-397099a69f05558cbf66f164cffcaf65.js');