CREATE TABLE IF NOT EXISTS `#__perfectpics_orders` (
	`id` int(11) unsigned NOT NULL AUTO_INCREMENT,
	`asset_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'FK to the #__assets table.',
	`catid` int(11) unsigned NOT NULL DEFAULT '0',
	`customers_name` VARCHAR(255) NOT NULL COMMENT 'Customers Names',
	`customers_email` VARCHAR(255) NOT NULL COMMENT 'Customers Email',
	`customers_phone` VARCHAR(255) NOT NULL COMMENT 'Customers Phone Number',
	`upload_pdf` VARCHAR(255) NOT NULL COMMENT 'Your PDF details',
	`book_size` VARCHAR(255) NOT NULL COMMENT 'book size',
	`cover_type` VARCHAR(255) NOT NULL COMMENT 'Your cover type',
	`paper_type` VARCHAR(255) NOT NULL COMMENT 'Your paper type',
	`book_title` VARCHAR(255) NOT NULL COMMENT 'Your book title',
	`author_name` VARCHAR(255) NOT NULL COMMENT 'Author name',
	`ordering` int(11) NOT NULL DEFAULT '0',
	`published` tinyint(3) NOT NULL DEFAULT '0',
	`checked_out` int(11) unsigned NOT NULL DEFAULT '0',
	`checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`created_by` int(11) unsigned NOT NULL DEFAULT '0',
	`modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified_by` int(11) unsigned NOT NULL DEFAULT '0',
	`publish_up` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`publish_down` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
	`access` int(11) unsigned NOT NULL DEFAULT '0',
	`params` text NOT NULL,
	`metadesc` text NOT NULL,
	PRIMARY KEY (id)
)
CHARACTER SET utf8
COLLATE utf8_general_ci;
